name: CI

on: [push, pull_request]

env: # Define environment variables here
  # NODE_VERSION: 20
  # PNPM_VERSION: 6 # Replace with the version of pnpm you want to use
  DATABASE_URL: http://database.url

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set up environment variables
        run: echo ${{ env.DATABASE_URL }} >> .env.local

      - name: Type checking
        run: pnpm run typecheck

      - name: Linting
        run: pnpm run lint
