name: CI

on: [push, pull_request]

env: # Define environment variables here
  # NODE_VERSION: 20
  # PNPM_VERSION: 6 # Replace with the version of pnpm you want to use
  DATABASE_URL: http://database.url

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # may have to espacify node version
      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm add

      - name: Run TypeScript type checking
        run: pnpm run typecheck

      - name: Run linting
        run: pnpm run lint

      - name: Log Node.js version
        run: echo $NODE_VERSION
