name: CI

on: [push, pull_request]

env:
  DATABASE_URL: http://database.url

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set up environment variables
        run: echo ${{ env.DATABASE_URL }} >> .env.local

      - name: Type checking
        run: pnpm run typecheck

      - name: Linting
        run: pnpm run lint

      - name: Lint Fix
        run: pnpm run lint --fix
